### ISSUE TITLE
allow argument n instead of epsilon

### ISSUE THREAD

**Issue by karlrohe** [RoheLab/aPPR#10]
would be super great to allow an argument n which would be the number of API request to twitter.  Stop after that many requests, compute what epsilon is (or kinda-sorta guess).

**Comment by alexpghayes** [comment]
This should be straightforward. Additionally, we can calculated the achieved epsilon and display it, which I think would be useful.

**Comment by alexpghayes** [comment]
See f792953441642759f04071341050e3eed34028ee. The argument is called `max_visits`.
